### ISSUE TITLE
Potential bug with the `identifyOutliers` check function

### ISSUE THREAD

**Issue by nischalshrestha** [ekstroem/dataReporter#4]
I was exploring the `dataReporter::identifyOutliers` function on the `airquality` dataset and I noticed the package reported `1` as being the outlier value which doesn't seem to make sense:

``` r
require(dataReporter)
#> Loading required package: dataReporter

# the value of 1 is suggested as outlier
identifyOutliers(airquality$Ozone)
#> Note that the following possible outlier values were detected: 1.

# however, `boxplot.stats` reports the more reasonable
# values for the outliers
boxplot.stats(airquality$Ozone)$out
#> [1] 135 168
```

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Could this be a bug perhaps? Please let me know if I'm not using the check correctly.

**Comment by nischalshrestha** [comment]
It looks like the `identifyOutliersTBStyle` is what I should use to align with the boxplot method:

``` r
require(dataReporter)
#> Loading required package: dataReporter
boxplot.stats(airquality$Ozone)$out
#> [1] 135 168
identifyOutliersTBStyle(airquality$Ozone)
#> Note that the following possible outlier values were detected: 135, 168.
```

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I can close this if the `identifyOutliers` check is behaving as expected!

**Comment by ekstroem** [comment]
It is a "feature" in the sense that the default underlying outlier detection algorithm is based on code from the `robustbase` package which has an asymmetric outlier detection approach that is different from the traditional Tukey limits.

The `identifyOutliersTBStyle` provides outliers that matches what is seen in the boxplots graphs.

So it is not a bug and you have found the workaround that produces results that resemble what is seen elsewhere in base R.
